version: '3'
services:
  mysql:
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
    environment:
      - MYSQL_ROOT_PASSWORD=root

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myproject
    ports:
      - "3000:3000"
    links:
      - "mysql"
